version: '3'

services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    # image: postgres-image
    # build:
    #   context: ./db/
    #   dockerfile: Dockerfile
    env_file: ./db/.env  
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      # - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network-app

  node-backend:
    container_name: node-backend
    # restart: always
    image: node-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file: ./backend/.env
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3001:3001"
    expose:
      - "3001"
    depends_on:
      - postgres
    networks:
      - network-app

  node-frontend:
    container_name: node-frontend
    image: node-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - node-backend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - network-app


volumes:
  pg_data:
networks:
  network-app: