# Global definitions.
// Default host.
http://localhost:3001
# -v
-s
-i
Accept: application/json
Content-Type: application/json; charset=utf-8
Connection: keep-alive
User-Agent: VRC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIkVtYWlsIjoibWFpbEBnbWFpbC5jb20iLCJBZG1pbiI6ZmFsc2UsImlhdCI6MTcxMzQ4NzUxMCwiZXhwIjoxNzEzNTczOTEwfQ.Sn1Pcy5xDb7tlFAw79bS_gVQdZxaexiAjD-QzbDIlCw

--

#
# Recuperar todos los productos
#
--
GET /Producto

#
# Recuperar todas las películas
#
--
GET /Producto/1

### Crear un nuevo Producto (Corregir)
--
POST /Producto
{
      "Nombre": "Maceta",
      "Disponible": 1,
      "Precio": 13.55,
      "Imagen": "https://url.com.ar",
      "Descripcion": "Un recipiente para plantar flores",
      "Genero": "Femenino",
      # "Activo": true,
      "StoreId": 1,
      "CategoryId": 1
}

### Recuperar todas las categorias
--
GET /Categoria


### Crear una nueva categoria (recurso / registro en db)
--
POST /Categoria
{
      "Nombre": "Accesorios"
}

# Crear nuevo usuario  ( Registro )
--
POST /Registro # (Michael Jackson)
{
      "Nombre": "Michael",
      "Apellido": "Jackson",
      "Email": "mail2@gmail.com",
      "Contraseña": "123456789"
}
# Crear admin  ( Registro )
--
POST /Registro # (Freddie Mercury)
{
      "Nombre": "Freddie",
      "Apellido": "Mercury",
      "Email": "admin123@gmail.com",
      "Contraseña": "12345678"
}

# Crear nuevo usuario  ( Registro )
--
POST /Registro # (Javier)
{
      "Nombre": "Javier",
      "Apellido": "Pignataro",
      "Email": "mail@gmail.com",
      "Contraseña": "123456789"
}

# Loguear un usuario
--
POST /Login # (Javier)
{
      "Email": "mail@gmail.com",
      "Contraseña": "123456789"
}

# Obtener usuarios ---> # En esta Request El JWT Debe ir en el header de "Authorization"
--
GET /Usuario

# Obtener usuario por id ( un unico usuario ) o Detalle de Usuario (ID) ---> # En esta Request El JWT Debe ir en el header de "Authorization"
--
GET /Usuario/2

# Editar / Modificar un usuario Por ID ---> # En esta Request El JWT Debe ir en el header de "Authorization"
--
PATCH /Usuario/2
{
      "Nombre": "Hector",
      "Apellido": "Soler",
      "Genero": "Masculino",
      "FechaNacimiento": "2024-04-13T22:17:12.837Z",
      "Ubicacion": "Buenos Aires, Argentina"
}

### Recuperar todas las tiendas
--
GET /Tienda


### Crear una tienda
--
POST /Tienda
{
      "Nombre": "Verduleria de la pasion",
      "Imagen": "http://urlfalsa.ultra.falsa"
}

### Modificar una tienda
--
PUT /Tienda
{
      "Id": "1",
      "Nombre": "Verduleria de la pasion",
      "Imagen": "google"
}


### Eliminar una tienda
--
DELETE /Tienda/4

### Eliminar Usuario
--
DELETE /Usuario/1

### Crear COMPRA
--
POST /Compra
{
      "Titulo": "Televisor artesanal",
      "UserId": 1,
      "ProductId": 1,
      "FechaCompra": "2024-04-13T22:17:12.837Z",
      "Cantidad": 5,
      "PrecioTotal": 500.0
}


