FROM postgres

WORKDIR /app

# COPY .env /app/.env

ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=asd123
ENV POSTGRES_DB=marketplace

EXPOSE 5432

# docker run --name postgres -p 5432:5432 --env-file .env postgres-image